apiVersion: v1
kind: Service
metadata:
  name: hellok8snodeapp-service
  labels:
    run: hellok8snodeapp-service
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: hellok8snodeapp
  type: NodePort