apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginxserver
    labels:
        app: my-app
        tier: usingrs
spec:
    template:
        metadata:
            name: nginx-rc
            labels:
                app: myappnginx
                type: backend-dev
        spec:
            containers:
                - name: nginx-rc-container
                  image: nginx
                  ports:
                    - containerPort: 80
    replicas: 2
    selector: 
        matchLabels:
            type: backend-dev