apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: greeter-ingress
spec:
  rules:
  - http:
      paths:
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80