apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-ext-deployment
  namespace: default
  labels:
    name: greeter-ext-deployment
    app: greet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-ext-pod
      app: greet-app
  template:
    metadata:
      name: greeter-ext-pod
      namespace: default
      labels:
        name: greeter-ext-pod
        app: greet-app
    spec:
      containers:
        - name: greeter-ext-container
          image: gcr.io/k8s-explore-309407/greeter-ext:v1
          ports:
            - containerPort: 3001
          env: 
            - name: GREETER_CORE_SERVICE
              value: http://104.197.193.49:3000/name?name=
