apiVersion: v1
kind: Pod
metadata:
    name: greeter-pod
    namespace: default
    labels:
        name: greeter-pod
        app:  greeter-node-app
spec:
    containers:
        - name: greeter-container
          image: greeter:v2
          imagePullPolicy: Never
          ports: 
            - containerPort: 3001
          env: 
            - name: HELLO_K8S_NODE_APP
            - value: http://192.168.64.2:30027/name?name=